# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Epicture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Epicture

  target 'EpictureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EpictureUITests' do
    # Pods for testing
  end

  pod 'Alamofire'
  pod 'SDWebImage'

end
